### ISSUE TITLE
create_topic_and_subscription.py refactoring

### ISSUE THREAD

**Issue by severyn-pkh** [mhordiyenko/Python_training#1]
1. To create Pull Request
2. function close to call
3. if __name__ == '__main__':
2. create_parser + parse -> return parsed parameters
3. Why lines 91-94 outside PubSubChecker?
4. check_inserted_params_and_run -> 2 responsibilities 
5. p - a bad name
6. Where subscriber object pass to the PubSubSubscriptionCreator? The same for PubSubTopicCreator creator
7. check_inserted_params_and_run - refactor
8. topic = PubSubTopicCreator(topic_path) :    topic --> topic_creator
9. PubSubTopicCreator and PubSubSubscriptionCreator can inherit a single interface

**Comment by mhordiyenko** [comment]
fixed
